#!/bin/bash

# Lint 검사
echo "🔍 Pre-commit Hook: Running lint checks..."
if yarn lint-staged; then
  echo "✅ Lint checks passed."
else
  echo "❌ Lint checks failed. Aborting commit."
  exit 1
fi

echo "🔍 Pre-commit Hook: Running test checks..."
if yarn test; then
  echo "✅ Test checks passed."
else
  echo "❌ Test checks failed. Aborting commit."
  exit 1
fi